version: '3'
services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    env_file: .env
    volumes:
      - bundle-data:/usr/local/bundle:cached
      - .:/usr/src/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
volumes:
  bundle-data:
  db-data:
